{{- if .Values.twitch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pedro-twitch
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pedro-twitch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: twitch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pedro-twitch
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.twitch.metrics.port }}
      targetPort: metrics
      protocol: TCP
    - name: oauth
      port: {{ .Values.twitch.oauth.port }}
      targetPort: oauth
      protocol: TCP
{{- end }}
