{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: pedro-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pedro.labels" . | nindent 4 }}
type: Opaque
stringData:
  llama-cpp-path: {{ .Values.secrets.llamaCppPath | quote }}
  postgres-url: {{ .Values.secrets.postgresUrl | quote }}
  postgres-vector-url: {{ .Values.secrets.postgresVectorUrl | quote }}
  discord-secret: {{ .Values.secrets.discordSecret | quote }}
  twitch-secret: {{ .Values.secrets.twitchSecret | quote }}
  twitch-id: {{ .Values.secrets.twitchId | quote }}
  model: {{ .Values.secrets.model | quote }}
{{- end }}
